### ISSUE TITLE
V3.0.0 + Errors

### ISSUE THREAD

**Issue by aaronbarnaby** [iwolfking/VHAPI#1]
When trying to update the vhapi version to v3.0.0 or v3.1.0 I get errors when trying to start client / join world.
Both versions seem to give different issues.

Without changing anything from my setup in v2.0.4

updating to v3.0.0 I can start the client but when trying to join world I get the following crash:

```
[14:16:03] [Server thread/FATAL] [ne.mi.fm.DistExecutor/]: Detected unsafe referent usage, please view the code at TRANSFORMER/vhapi@3.0.0/xyz.iwolfking.vhapi.VHAPI.onLogin(VHAPI.java:97)
[14:16:03] [Server thread/ERROR] [ne.mi.ev.EventBus/EVENTBUS]: Exception caught during firing event: Unsafe Referent usage found in safe referent method
	Index: 27
	Listeners:
		0: HIGH
		1: ASM: class dev.architectury.event.forge.EventHandlerImplCommon event(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		2: NORMAL
		3: net.minecraftforge.eventbus.EventBus$$Lambda$4761/0x0000019437b97070@7406f8eb
		4: ASM: com.mrbysco.chunkymcchunkface.handler.PlayerHandler@4efcd3d1 onPlayerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		5: net.minecraftforge.eventbus.EventBus$$Lambda$4761/0x0000019437b97070@76d09f64
		6: ASM: class com.github.alexthe666.alexsmobs.event.ServerEvents onPlayerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		7: ASM: net.minecraftforge.common.ForgeInternalHandler@4ea5627a playerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		8: ASM: class dev.architectury.networking.forge.NetworkManagerImpl loggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		9: net.minecraftforge.eventbus.EventBus$$Lambda$4761/0x0000019437b97070@407a705f
		10: ASM: class com.aaronbarnaby.grownupmod.events.DataPullEvents onPlayerJoin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		11: net.minecraftforge.eventbus.EventBus$$Lambda$4761/0x0000019437b97070@35889055
		12: ASM: class iskallia.vault.event.PlayerEvents onInvalidConfigs(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		13: ASM: class iskallia.vault.event.PlayerEvents onPatreonLoad(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		14: ASM: class iskallia.vault.event.SpecialEvents joiningWorldEvent(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		15: ASM: class iskallia.vault.util.PlayerResearchTransferUtil onPlayerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		16: ASM: class iskallia.vault.util.damage.PlayerDamageHelper on(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		17: ASM: class iskallia.vault.world.data.AchievementData onPlayerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		18: ASM: class iskallia.vault.world.data.QuestStatesData onPlayerJoin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		19: ASM: class iskallia.vault.world.data.GodAltarData onPlayerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		20: ASM: class iskallia.vault.world.data.BountyData onPlayerJoin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		21: ASM: class iskallia.vault.world.data.PlayerTitlesData onPlayerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		22: ASM: class iskallia.vault.world.data.ParadoxCrystalData onPlayerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		23: ASM: vazkii.quark.content.tweaks.module.AutomaticRecipeUnlockModule@325d2cd0 onPlayerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		24: ASM: top.theillusivec4.curios.common.event.CuriosEventHandler@2d2949bf playerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		25: ASM: mekanism.common.CommonPlayerTracker@6a63c475 onPlayerLoginEvent(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		26: LOWEST
		27: net.minecraftforge.eventbus.EventBus$$Lambda$4761/0x0000019437b97070@768ae7af
java.lang.RuntimeException: Unsafe Referent usage found in safe referent method
	at LAYER PLUGIN/fmlcore@1.18.2-40.2.9/net.minecraftforge.fml.DistExecutor.validateSafeReferent(DistExecutor.java:254)
	at LAYER PLUGIN/fmlcore@1.18.2-40.2.9/net.minecraftforge.fml.DistExecutor.safeRunWhenOn(DistExecutor.java:121)
	at TRANSFORMER/vhapi@3.0.0/xyz.iwolfking.vhapi.VHAPI.onLogin(VHAPI.java:97)
	at MC-BOOTSTRAP/eventbus@5.0.7/net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)
	at MC-BOOTSTRAP/eventbus@5.0.7/net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239)
	at MC-BOOTSTRAP/eventbus@5.0.7/net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at MC-BOOTSTRAP/eventbus@5.0.7/net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at TRANSFORMER/forge@40.2.9/net.minecraftforge.event.ForgeEventFactory.firePlayerLoggedIn(ForgeEventFactory.java:833)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:238)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.network.ServerLoginPacketListenerImpl.placeNewPlayer(ServerLoginPacketListenerImpl.java:138)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.network.ServerLoginPacketListenerImpl.handleAcceptedLogin(ServerLoginPacketListenerImpl.java:125)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.network.ServerLoginPacketListenerImpl.tick(ServerLoginPacketListenerImpl.java:69)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.network.Connection.tick(Connection.java:241)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:143)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:916)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:842)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.server.IntegratedServer.tickServer(IntegratedServer.java:84)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:685)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:261)
	at java.base/java.lang.Thread.run(Thread.java:840)
[14:16:03] [Server thread/ERROR] [minecraft/ServerLoginPacketListenerImpl]: Couldn't place player in world
java.lang.RuntimeException: Unsafe Referent usage found in safe referent method
	at net.minecraftforge.fml.DistExecutor.validateSafeReferent(DistExecutor.java:254) ~[fmlcore-1.18.2-40.2.9.jar%2384!/:?] {}
	at net.minecraftforge.fml.DistExecutor.safeRunWhenOn(DistExecutor.java:121) ~[fmlcore-1.18.2-40.2.9.jar%2384!/:?] {}
	at xyz.iwolfking.vhapi.VHAPI.onLogin(VHAPI.java:97) ~[vault-hunters-api-1118899-5857191_mapped_official_1.18.2.jar%2391!/:3.0.0] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-5.0.7.jar%2316!/:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-5.0.7.jar%2316!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.7.jar%2316!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.7.jar%2316!/:?] {}
	at net.minecraftforge.event.ForgeEventFactory.firePlayerLoggedIn(ForgeEventFactory.java:833) ~[forge-1.18.2-40.2.9_mapped_official_1.18.2.jar%2379%2386!/:?] {re:classloading}
	at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:238) ~[forge-1.18.2-40.2.9_mapped_official_1.18.2.jar%2380!/:?] {re:mixin,re:classloading}
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.placeNewPlayer(ServerLoginPacketListenerImpl.java:138) ~[forge-1.18.2-40.2.9_mapped_official_1.18.2.jar%2380!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.handleAcceptedLogin(ServerLoginPacketListenerImpl.java:125) ~[forge-1.18.2-40.2.9_mapped_official_1.18.2.jar%2380!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.tick(ServerLoginPacketListenerImpl.java:69) ~[forge-1.18.2-40.2.9_mapped_official_1.18.2.jar%2380!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.network.Connection.tick(Connection.java:241) ~[forge-1.18.2-40.2.9_mapped_official_1.18.2.jar%2380!/:?] {re:classloading}
	at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:143) ~[forge-1.18.2-40.2.9_mapped_official_1.18.2.jar%2380!/:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:916) ~[forge-1.18.2-40.2.9_mapped_official_1.18.2.jar%2380!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:assets/the_vault/the_vault.mixins.json:AccessorMinecraftServer,pl:mixin:APP:assets/the_vault/the_vault.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:842) ~[forge-1.18.2-40.2.9_mapped_official_1.18.2.jar%2380!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:assets/the_vault/the_vault.mixins.json:AccessorMinecraftServer,pl:mixin:APP:assets/the_vault/the_vault.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.tickServer(IntegratedServer.java:84) ~[forge-1.18.2-40.2.9_mapped_official_1.18.2.jar%2380!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:685) ~[forge-1.18.2-40.2.9_mapped_official_1.18.2.jar%2380!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:assets/the_vault/the_vault.mixins.json:AccessorMinecraftServer,pl:mixin:APP:assets/the_vault/the_vault.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:261) ~[forge-1.18.2-40.2.9_mapped_official_1.18.2.jar%2380!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:assets/the_vault/the_vault.mixins.json:AccessorMinecraftServer,pl:mixin:APP:assets/the_vault/the_vault.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:840) [?:?] {}
[14:16:03] [Server thread/INFO] [minecraft/ServerGamePacketListenerImpl]: Dev lost connection: Invalid player data
```

With version v3.1.0 the crash happens when loading client.

```
java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:55) ~[forge-1.18.2-40.2.9_mapped_official_1.18.2.jar%2379%2386!/:?] {re:classloading}
	at net.minecraftforge.client.loading.ClientModLoader.completeModLoading(ClientModLoader.java:170) ~[forge-1.18.2-40.2.9_mapped_official_1.18.2.jar%2379%2386!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$new$1(Minecraft.java:557) ~[forge-1.18.2-40.2.9_mapped_official_1.18.2.jar%2380!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ae2.mixins.json:PickColorMixin,pl:mixin:APP:ispawner-common.mixins.json:MixinMinecraftClient,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:assets/the_vault/the_vault.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.Util.ifElse(Util.java:397) ~[forge-1.18.2-40.2.9_mapped_official_1.18.2.jar%2380!/:?] {re:classloading,re:mixin}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:551) ~[forge-1.18.2-40.2.9_mapped_official_1.18.2.jar%2380!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ae2.mixins.json:PickColorMixin,pl:mixin:APP:ispawner-common.mixins.json:MixinMinecraftClient,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:assets/the_vault/the_vault.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.LoadingOverlay.render(LoadingOverlay.java:135) ~[forge-1.18.2-40.2.9_mapped_official_1.18.2.jar%2380!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.render(GameRenderer.java:879) ~[forge-1.18.2-40.2.9_mapped_official_1.18.2.jar%2380!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:assets/the_vault/the_vault.mixins.json:MixinGameRenderer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1046) ~[forge-1.18.2-40.2.9_mapped_official_1.18.2.jar%2380!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ae2.mixins.json:PickColorMixin,pl:mixin:APP:ispawner-common.mixins.json:MixinMinecraftClient,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:assets/the_vault/the_vault.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.run(Minecraft.java:665) ~[forge-1.18.2-40.2.9_mapped_official_1.18.2.jar%2380!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ae2.mixins.json:PickColorMixin,pl:mixin:APP:ispawner-common.mixins.json:MixinMinecraftClient,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:assets/the_vault/the_vault.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[forge-1.18.2-40.2.9_mapped_official_1.18.2.jar%2380!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:569) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.ForgeClientUserdevLaunchHandler.lambda$launchService$0(ForgeClientUserdevLaunchHandler.java:24) ~[fmlloader-1.18.2-40.2.9.jar%230!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%2317!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%2317!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%2317!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%2317!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%2317!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%2317!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%2317!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraftforge.fml.DistExecutor.validateSafeReferent(DistExecutor.java:254) ~[fmlcore-1.18.2-40.2.9.jar%2384!/:?] {}
-- MOD vhapi --
Details:
	Caused by 0: java.lang.reflect.InvocationTargetException
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
		at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstance(Constructor.java:481) ~[?:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:67) ~[javafmllanguage-1.18.2-40.2.9.jar%2381!/:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:106) ~[fmlcore-1.18.2-40.2.9.jar%2384!/:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

	Mod File: /C:/Users/Shadow/.gradle/caches/forge_gradle/deobf_dependencies/curse/maven/vault-hunters-api-1118899/5865552_mapped_official_1.18.2/vault-hunters-api-1118899-5865552_mapped_official_1.18.2.jar
	Failure message: VHAPI (vhapi) has failed to load correctly
		java.lang.reflect.InvocationTargetException: null
	Mod Version: 3.1.0
	Mod Issue URL: NOT PROVIDED
	Exception message: java.lang.RuntimeException: Unsafe Referent usage found in safe referent method
Stacktrace:
	at net.minecraftforge.fml.DistExecutor.validateSafeReferent(DistExecutor.java:254) ~[fmlcore-1.18.2-40.2.9.jar%2384!/:?] {}
	at net.minecraftforge.fml.DistExecutor.safeRunWhenOn(DistExecutor.java:121) ~[fmlcore-1.18.2-40.2.9.jar%2384!/:?] {}
	at xyz.iwolfking.vhapi.VHAPI.<init>(VHAPI.java:72) ~[vault-hunters-api-1118899-5865552_mapped_official_1.18.2.jar%2391!/:3.1.0] {re:classloading}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:481) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:67) ~[javafmllanguage-1.18.2-40.2.9.jar%2381!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:106) ~[fmlcore-1.18.2-40.2.9.jar%2384!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}
```

What am I doing wrong that's causing this or is there a issue making these versions not usable?

**Comment by aaronbarnaby** [comment]
Update:

May of actually fixed my own issue.  Typical that posting about it helps you identify where the issue might be.

I was running on Forge 40.2.9. (as per Vault Hunters modpack version)
however updating to Forget 40.2.21 seems to let v3.1.0 now run and connect to game.

Might be worth a breaking change notice on the version about that?

**Comment by aaronbarnaby** [comment]
I tried updating forge version to 40.2.21 (previously was on VH version of 40.2.9) 
Same error when I update to v3.0.0 and v3.1.0

**Comment by iwolfking** [comment]
First I have seen of this so far.

This has to do with some functionality to have certain code only run on client/server, but Forge is having an issue with it for some reason.

You shouldn't really be getting this error as I and many others don't have this issue but I will see if there is anything I can do here. Do you have any other additional mods?

**Comment by aaronbarnaby** [comment]
I found the issue was down to:
```
DistExecutor.safeRunWhenOn(Dist.CLIENT, () -> () -> {
   MinecraftForge.EVENT_BUS.addListener(Client::onClientLogin);
});
```

I've replaced with
```
if (FMLEnvironment.dist == Dist.CLIENT) {
  MinecraftForge.EVENT_BUS.addListener(Client::onVHAPIProcessorEnd);
  MinecraftForge.EVENT_BUS.addListener(Client::onClientLogin);
}
```

this seems to fix the issue for me, also adding the `onVHAPIProcessorEnd` here to handle manual registering the config files when joining server, shame to have to manually register but it's a solution for now :).

I can only assume i'm having more issue as I'm adding into a mod and not as a simple datapack.

Either way I found a solution so all good :)

**Comment by iwolfking** [comment]
Thanks, glad you found a solution for now. I did originally have this more like that, but had ran into issues when actually going to use it on a server. 

Not sure why you had this issue still though, this method has never been an issue for me.

If you are wanting to register some config files via mod, I may recommend looking at VHAPIProcessorUtils, you can register a file to be loaded, would just need the resource location to match the right path for the config you are loading

Wold's Standalone is a good example of this: 
 https://onedev.iwolfking.xyz/WoldsVaultsStandalone/~files/master/src/main/java/xyz/iwolfking/woldsvaults/events/SetupEvents.java

Or Scaling Bingo Seals:
https://github.com/iwolfking/ScalingBingoSeals/blob/master/src/main/java/xyz/iwolfking/scalingbingoseals/init/VHAPIIntegration.java
